### PR TITLE
composer: allow instal with PHP 8.0 code

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Any ETA on this? It's the last blocker for Rector to use PHP 8.0
https://github.com/rectorphp/rector/pull/4082/checks?check_run_id=1083741640

**Comment by moufmouf** [comment]
Sorry, I skiped the first notification. Let's merge this!

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Any ETA on tagging so I can use it as 3rd party dependency? 
I had to remove it from Rector for now, because the CI does not allow me to install it on PHP 8.0 and we need stable dependencies

**Comment by moufmouf** [comment]
Hey Tomas!

It is tagged: https://github.com/thecodingmachine/phpstan-strict-rules/releases/tag/v0.12.1

**Comment by TomasVotruba** [comment]
Epic support 👏 thank you

**Pull request merged**
